apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: exclusive-cpu
spec:
  selectors:
    - cel:
        expression: device.driver == "rte.nrt"
---
apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: shared-cpu
spec:
  selectors:
    - cel:
        expression: device.driver == "rte.nrt"
---